'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

fib_nums = [0,1]

while fib_nums[-1] < 4000000:
    point = len(fib_nums) - 1
    fib_nums.append(fib_nums[point - 1] + fib_nums[point])

even_vals = [num for count, num in enumerate(fib_nums) if (fib_nums[count] % 2 == 0)]
print(sum(even_vals))




    
